# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Controller-Rose
version:      0.04
version_from: lib/Catalyst/Controller/Rose.pm
installdirs:  site
requires:
    Data::Pageset:                 0.01
    JSON::Syck:                    0.01
    Rose::HTMLx::Form::Field::Autocomplete: 0.01
    Sort::SQL:                     0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
